apiVersion: v1
kind: Service
metadata:
  name: predictive-maintenance-service
spec:
  type: NodePort
  selector:
    app: predictive-maintenance
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30500